In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'c:\\Users\\ADMIN\\OneDrive\\Desktop\\WORKSHOP'

In [3]:
df=pd.read_csv('dataset/retail_sales_customer_analytics_dataset.csv')

In [4]:
df.shape

(2000, 22)

In [5]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Branch', 'Product',
       'Product_Category', 'Order_Date', 'Quantity', 'Unit_Price',
       'Discount_Percent', 'Gross_Revenue', 'Cost', 'Net_Sales', 'Profit',
       'Payment_Method', 'Customer_Type', 'Sales_Channel', 'Order_Status',
       'Return_Status', 'Customer_Feedback', 'Rating', 'Year'],
      dtype='str')

In [6]:
list(df.columns)

['Order_ID',
 'Customer_ID',
 'Customer_Name',
 'Branch',
 'Product',
 'Product_Category',
 'Order_Date',
 'Quantity',
 'Unit_Price',
 'Discount_Percent',
 'Gross_Revenue',
 'Cost',
 'Net_Sales',
 'Profit',
 'Payment_Method',
 'Customer_Type',
 'Sales_Channel',
 'Order_Status',
 'Return_Status',
 'Customer_Feedback',
 'Rating',
 'Year']

In [8]:
df.loc[:,['Customer_Name','Branch']]

      Customer_Name     Branch
0      Mary Wanjiku      Thika
1     David Kariuki    Eldoret
2      Peter Otieno     Kisumu
3               NaN     Nakuru
4       John Mwangi      Thika
...             ...        ...
1995  David Kariuki      Nyeri
1996   Amina Hassan  Westlands
1997            NaN     Kisumu
1998   Peter Otieno      Thika
1999   Peter Otieno    Eldoret

[2000 rows x 2 columns]

In [10]:
df['Rating'].value_counts()

Rating
1.0    313
4.0    311
2.0    292
3.0    274
5.0    267
7.0    262
Name: count, dtype: int64

In [18]:
df.loc[
    df['Rating'].isin([1,3, 5,7]),
    ['Customer_Name','Customer_ID','Product','Branch']
]

      Customer_Name Customer_ID    Product       Branch
1     David Kariuki    CUST1359    Printer      Eldoret
2      Peter Otieno    CUST1049        UPS       Kisumu
6      Mary Wanjiku    CUST1185  Projector        Thika
7     David Kariuki    CUST1128    Desktop  Nairobi CBD
8               NaN    CUST1430    Monitor       Nakuru
...             ...         ...        ...          ...
1989  David Kariuki    CUST1116        UPS      Mombasa
1995  David Kariuki    CUST1119  Projector        Nyeri
1996   Amina Hassan    CUST1230        UPS    Westlands
1997            NaN    CUST1080     Laptop       Kisumu
1998   Peter Otieno    CUST1304    Desktop        Thika

[1116 rows x 4 columns]