In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.8 MB 146.5 kB/s eta 0:01:04
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.8 MB 148.2 kB/s eta 0:01:01
   ---- ----------------------------------- 1.0/9.8 MB 149.8 kB/s eta 0:00:59
   ---- ----------------------------------- 1.0/9.8 MB 149.8 kB/s eta 0:00:59
   ---- ----------------------------------- 1.0/9.8 MB 149.8 kB/s eta 0:00:59
   ---- ----------------------------------- 1.0/9.8 MB 149.8 kB/s eta 0:00:59
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ----- ---------------------------------- 1.3/9.8 MB 168.6 kB/s eta 0:00:51
   ------ --------------------------------- 1.6/9.8 MB 178.8 kB/s eta 0:00:46
   ------ --------------------------------- 1.6/9.8 MB 178.8 kB/s eta 0:00:46
   ------ --------------------------------- 1.6/9.8 MB 178.8 kB/s eta 0:00:46
   ------- -------------------------------- 1.8/9.8 MB 195.6 kB/s eta 0:00:41
   ------- -------------------------------- 1.8/9.8 MB 195.6 kB/s eta 0:00:41
   -------- ------------------------------- 2.1/9.8 MB 215.7 kB/s eta 0:00:36
   -------- ------------------------------- 2.1/9.8 MB 215.7 kB/s eta 0:00:36
   -------- ------------------------------- 2.1/9.8 MB 215.7 kB/s eta 0:00:36
   -------- ------------------------------- 2.1/9.8 MB 215.7 kB/s eta 0:00:36
   --------- ------------------------------ 2.4/9.8 MB 225.0 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 225.0 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 225.0 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 225.0 kB/s eta 0:00:34
   ---------- ----------------------------- 2.6/9.8 MB 233.1 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 233.1 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 233.1 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 233.1 kB/s eta 0:00:31
   ----------- ---------------------------- 2.9/9.8 MB 237.9 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 237.9 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 237.9 kB/s eta 0:00:30
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------ --------------------------- 3.1/9.8 MB 245.9 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 234.7 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 234.7 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 234.7 kB/s eta 0:00:28
   -------------- ------------------------- 3.7/9.8 MB 243.9 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.8 MB 243.9 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.8 MB 243.9 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.8 MB 243.9 kB/s eta 0:00:26
   -------------- ------------------------- 3.7/9.8 MB 243.9 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ---------------- ----------------------- 3.9/9.8 MB 242.9 kB/s eta 0:00:25
   ------------------- -------------------- 4.7/9.8 MB 269.0 kB/s eta 0:00:19
   ------------------- -------------------- 4.7/9.8 MB 269.0 kB/s eta 0:00:19
   ------------------- -------------------- 4.7/9.8 MB 269.0 kB/s eta 0:00:19
   ------------------- -------------------- 4.7/9.8 MB 269.0 kB/s eta 0:00:19
   -------------------- ------------------- 5.0/9.8 MB 270.4 kB/s eta 0:00:18
   -------------------- ------------------- 5.0/9.8 MB 270.4 kB/s eta 0:00:18
   -------------------- ------------------- 5.0/9.8 MB 270.4 kB/s eta 0:00:18
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/9.8 MB 276.6 kB/s eta 0:00:17
   ---------------------- ----------------- 5.5/9.8 MB 268.7 kB/s eta 0:00:16
   ---------------------- ----------------- 5.5/9.8 MB 268.7 kB/s eta 0:00:16
   ---------------------- ----------------- 5.5/9.8 MB 268.7 kB/s eta 0:00:16
   ---------------------- ----------------- 5.5/9.8 MB 268.7 kB/s eta 0:00:16
   ----------------------- ---------------- 5.8/9.8 MB 270.9 kB/s eta 0:00:15
   ----------------------- ---------------- 5.8/9.8 MB 270.9 kB/s eta 0:00:15
   ----------------------- ---------------- 5.8/9.8 MB 270.9 kB/s eta 0:00:15
   ------------------------ --------------- 6.0/9.8 MB 274.6 kB/s eta 0:00:14
   ------------------------ --------------- 6.0/9.8 MB 274.6 kB/s eta 0:00:14
   ------------------------ --------------- 6.0/9.8 MB 274.6 kB/s eta 0:00:14
   ------------------------ --------------- 6.0/9.8 MB 274.6 kB/s eta 0:00:14
   ------------------------ --------------- 6.0/9.8 MB 274.6 kB/s eta 0:00:14
   ------------------------- -------------- 6.3/9.8 MB 273.0 kB/s eta 0:00:13
   ------------------------- -------------- 6.3/9.8 MB 273.0 kB/s eta 0:00:13
   ------------------------- -------------- 6.3/9.8 MB 273.0 kB/s eta 0:00:13
   ------------------------- -------------- 6.3/9.8 MB 273.0 kB/s eta 0:00:13
   ------------------------- -------------- 6.3/9.8 MB 273.0 kB/s eta 0:00:13
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/9.8 MB 272.4 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   --------------------------- ------------ 6.8/9.8 MB 260.5 kB/s eta 0:00:12
   ---------------------------- ----------- 7.1/9.8 MB 256.4 kB/s eta 0:00:11
   ---------------------------- ----------- 7.1/9.8 MB 256.4 kB/s eta 0:00:11
   ---------------------------- ----------- 7.1/9.8 MB 256.4 kB/s eta 0:00:11
   ---------------------------- ----------- 7.1/9.8 MB 256.4 kB/s eta 0:00:11
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   ----------------------------- ---------- 7.3/9.8 MB 258.6 kB/s eta 0:00:10
   -------------------------------- ------- 7.9/9.8 MB 255.8 kB/s eta 0:00:08
   -------------------------------- ------- 7.9/9.8 MB 255.8 kB/s eta 0:00:08
   --------------------------------- ------ 8.1/9.8 MB 268.6 kB/s eta 0:00:07
   --------------------------------- ------ 8.1/9.8 MB 268.6 kB/s eta 0:00:07
   --------------------------------- ------ 8.1/9.8 MB 268.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.8 MB 271.6 kB/s eta 0:00:06
   ---------------------------------- ----- 8.4/9.8 MB 271.6 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ----------------------------------- ---- 8.7/9.8 MB 276.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 281.3 kB/s eta 0:00:04
   ------------------------------------ --- 8.9/9.8 MB 281.3 kB/s eta 0:00:04
   ------------------------------------ --- 8.9/9.8 MB 281.3 kB/s eta 0:00:04
   ------------------------------------ --- 8.9/9.8 MB 281.3 kB/s eta 0:00:04
   ------------------------------------- -- 9.2/9.8 MB 282.4 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 282.4 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 282.4 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 282.4 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.8 MB 291.1 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 291.1 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 291.1 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 291.1 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 291.1 kB/s eta 0:00:02
   ---------------------------------------  9.7/9.8 MB 289.2 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 290.1 kB/s  0:00:37
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 338.2 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.7 MB 338.2 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.7 MB 338.2 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.7 MB 338.2 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.7 MB 338.2 kB/s eta 0:00:36
   -- ------------------------------------- 0.8/12.7 MB 310.5 kB/s eta 0:00:39
   -- ------------------------------------- 0.8/12.7 MB 310.5 kB/s eta 0:00:39
   -- ------------------------------------- 0.8/12.7 MB 310.5 kB/s eta 0:00:39
   --- ------------------------------------ 1.0/12.7 MB 312.6 kB/s eta 0:00:38
   --- ------------------------------------ 1.0/12.7 MB 312.6 kB/s eta 0:00:38
   --- ------------------------------------ 1.0/12.7 MB 312.6 kB/s eta 0:00:38
   --- ------------------------------------ 1.0/12.7 MB 312.6 kB/s eta 0:00:38
   ---- ----------------------------------- 1.3/12.7 MB 318.8 kB/s eta 0:00:36
   ---- ----------------------------------- 1.3/12.7 MB 318.8 kB/s eta 0:00:36
   ---- ----------------------------------- 1.3/12.7 MB 318.8 kB/s eta 0:00:36
   ---- ----------------------------------- 1.3/12.7 MB 318.8 kB/s eta 0:00:36
   ---- ----------------------------------- 1.3/12.7 MB 318.8 kB/s eta 0:00:36
   ---- ----------------------------------- 1.6/12.7 MB 303.1 kB/s eta 0:00:37
   ---- ----------------------------------- 1.6/12.7 MB 303.1 kB/s eta 0:00:37
   ---- ----------------------------------- 1.6/12.7 MB 303.1 kB/s eta 0:00:37
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.7 MB 319.1 kB/s eta 0:00:35
   ------ --------------------------------- 2.1/12.7 MB 285.6 kB/s eta 0:00:38
   ------ --------------------------------- 2.1/12.7 MB 285.6 kB/s eta 0:00:38
   ------ --------------------------------- 2.1/12.7 MB 285.6 kB/s eta 0:00:38
   -------- ------------------------------- 2.6/12.7 MB 326.8 kB/s eta 0:00:31
   -------- ------------------------------- 2.6/12.7 MB 326.8 kB/s eta 0:00:31
   -------- ------------------------------- 2.6/12.7 MB 326.8 kB/s eta 0:00:31
   --------- ------------------------------ 2.9/12.7 MB 336.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.9/12.7 MB 336.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.9/12.7 MB 336.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.9/12.7 MB 336.4 kB/s eta 0:00:30
   --------- ------------------------------ 3.1/12.7 MB 332.8 kB/s eta 0:00:29
   --------- ------------------------------ 3.1/12.7 MB 332.8 kB/s eta 0:00:29
   --------- ------------------------------ 3.1/12.7 MB 332.8 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.4/12.7 MB 336.2 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.7 MB 322.5 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.7 MB 322.5 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.7 MB 322.5 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.7 MB 322.5 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.7 MB 322.5 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.7 MB 313.4 kB/s eta 0:00:28

In [3]:
import pandas as pd
import os

In [5]:
print(os.getcwd())

c:\Users\ADMIN\OneDrive\Desktop\WORKSHOP

In [7]:
print(os.listdir())

['.git', '.ipynb_checkpoints', '.venv', 'dataset', 'Missing_Values_Analysis.ipynb', 'Retail_sales_customer_analysis.ipynb']

In [8]:
os.listdir("dataset")

['Net_Sales_Branch_Product.csv', 'retail_sales_customer_analytics_dataset.csv']

In [9]:
df = pd.read_csv("dataset/retail_sales_customer_analytics_dataset.csv")

In [10]:
df.head()

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,-5.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,-5.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,0.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,-5.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,-5.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0

In [12]:
df.shape

(2000, 22)

In [13]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Branch', 'Product',
       'Product_Category', 'Order_Date', 'Quantity', 'Unit_Price',
       'Discount_Percent', 'Gross_Revenue', 'Cost', 'Net_Sales', 'Profit',
       'Payment_Method', 'Customer_Type', 'Sales_Channel', 'Order_Status',
       'Return_Status', 'Customer_Feedback', 'Rating', 'Year'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           2000 non-null   str
 1   Customer_ID        2000 non-null   str
 2   Customer_Name      1664 non-null   str
 3   Branch             2000 non-null   str
 4   Product            2000 non-null   str
 5   Product_Category   2000 non-null   str
 6   Order_Date         2000 non-null   str
 7   Quantity           1719 non-null   float64
 8   Unit_Price         1723 non-null   float64
 9   Discount_Percent   1680 non-null   float64
 10  Gross_Revenue      1480 non-null   float64
 11  Cost               1719 non-null   float64
 12  Net_Sales          1245 non-null   float64
 13  Profit             1245 non-null   float64
 14  Payment_Method     1613 non-null   str
 15  Customer_Type      1484 non-null   str
 16  Sales_Channel      1507 non-null   str
 17  Order_Status       1475 non-null   str
 18  Return_Status      1601 non-null   str
 19  Customer_Feedback  1518 non-null   str
 20  Rating             1719 non-null   float64
 21  Year               1346 non-null   float64
dtypes: float64(9), str(13)
memory usage: 343.9 KB

In [15]:
df.head(10)

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,-5.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,-5.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,0.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,-5.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,-5.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0
5,ORD10005,CUST1137,John Mwangi,Nakuru,UPS,Networking,2025-02-27,5.0,1500.0,10.0,...,6750.0,-83250.0,Card,NaN,NaN,NaN,No,Dissatisfied,2.0,2025.0
6,ORD10006,CUST1185,Mary Wanjiku,Thika,Projector,Office Equipment,2026-07-29,10.0,NaN,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Cancelled,No,NaN,5.0,2025.0
7,ORD10007,CUST1128,David Kariuki,Nairobi CBD,Desktop,Networking,2026-01-30,NaN,-500.0,NaN,...,NaN,NaN,Mobile Money,Individual,Phone,NaN,No,NaN,1.0,NaN
8,ORD10008,CUST1430,NaN,Nakuru,Monitor,Networking,2025-09-27,3.0,5000.0,-5.0,...,15750.0,-8250.0,Card,Individual,Phone,NaN,Yes,Satisfied,3.0,2026.0
9,ORD10009,CUST1043,NaN,Nyeri,Desktop,Accessories,2025-09-03,1.0,25000.0,NaN,...,NaN,NaN,Card,NaN,Online,Pending,NaN,NaN,2.0,NaN

In [16]:
df.tail(10)

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
1990,ORD11594,CUST1339,NaN,Kisumu,Printer,Computers,2025-10-20,NaN,85000.0,15.0,...,NaN,NaN,Bank Transfer,Individual,NaN,Cancelled,Yes,Satisfied,2.0,NaN
1991,ORD11925,CUST1104,Amina Hassan,Eldoret,Printer,Accessories,2025-04-04,1.0,12000.0,-5.0,...,12600.0,-5400.0,Mobile Money,NaN,NaN,Cancelled,No,Neutral,NaN,2025.0
1992,ORD11225,CUST1033,Amina Hassan,Eldoret,Laptop,Computers,2025-10-19,-2.0,50000.0,NaN,...,NaN,NaN,NaN,Individual,Physical Store,Completed,YES,NaN,4.0,NaN
1993,ORD10846,CUST1158,Peter Otieno,Nyeri,Projector,Accessories,2025-01-24,-2.0,25000.0,-5.0,...,-52500.0,-46500.0,Bank Transfer,Institution,Phone,Pending,Yes,NaN,4.0,2025.0
1994,ORD11881,CUST1212,Peter Otieno,Kisumu,Projector,Computers,2026-09-24,1.0,25000.0,15.0,...,21250.0,20450.0,Cash,Institution,Phone,NaN,No,Dissatisfied,4.0,2026.0
1995,ORD11410,CUST1119,David Kariuki,Nyeri,Projector,Computers,2026-08-12,10.0,50000.0,15.0,...,425000.0,395000.0,Mobile Money,Business,Physical Store,Pending,no,NaN,3.0,2025.0
1996,ORD11515,CUST1230,Amina Hassan,Westlands,UPS,Accessories,2026-07-21,5.0,-500.0,NaN,...,NaN,NaN,Bank Transfer,Institution,Online,Pending,YES,Satisfied,5.0,2026.0
1997,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0
1998,ORD10830,CUST1304,Peter Otieno,Thika,Desktop,Accessories,2025-11-02,5.0,85000.0,10.0,...,382500.0,207500.0,Cash,Institution,NaN,Completed,No,NaN,1.0,2025.0
1999,ORD10859,CUST1318,Peter Otieno,Eldoret,Mouse,Computers,2026-06-18,1.0,25000.0,10.0,...,22500.0,14500.0,Mobile Money,Individual,Online,NaN,no,Dissatisfied,4.0,2026.0

In [17]:
df = df.drop(columns=["No."], errors="ignore")

df.insert(0, "No.", range(1, len(df) + 1))

In [18]:
df.head(10)

,No.,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,1,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,2,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,3,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,4,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,5,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0
5,6,ORD10005,CUST1137,John Mwangi,Nakuru,UPS,Networking,2025-02-27,5.0,1500.0,...,6750.0,-83250.0,Card,NaN,NaN,NaN,No,Dissatisfied,2.0,2025.0
6,7,ORD10006,CUST1185,Mary Wanjiku,Thika,Projector,Office Equipment,2026-07-29,10.0,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Cancelled,No,NaN,5.0,2025.0
7,8,ORD10007,CUST1128,David Kariuki,Nairobi CBD,Desktop,Networking,2026-01-30,NaN,-500.0,...,NaN,NaN,Mobile Money,Individual,Phone,NaN,No,NaN,1.0,NaN
8,9,ORD10008,CUST1430,NaN,Nakuru,Monitor,Networking,2025-09-27,3.0,5000.0,...,15750.0,-8250.0,Card,Individual,Phone,NaN,Yes,Satisfied,3.0,2026.0
9,10,ORD10009,CUST1043,NaN,Nyeri,Desktop,Accessories,2025-09-03,1.0,25000.0,...,NaN,NaN,Card,NaN,Online,Pending,NaN,NaN,2.0,NaN

In [19]:
df.tail(10)

,No.,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
1990,1991,ORD11594,CUST1339,NaN,Kisumu,Printer,Computers,2025-10-20,NaN,85000.0,...,NaN,NaN,Bank Transfer,Individual,NaN,Cancelled,Yes,Satisfied,2.0,NaN
1991,1992,ORD11925,CUST1104,Amina Hassan,Eldoret,Printer,Accessories,2025-04-04,1.0,12000.0,...,12600.0,-5400.0,Mobile Money,NaN,NaN,Cancelled,No,Neutral,NaN,2025.0
1992,1993,ORD11225,CUST1033,Amina Hassan,Eldoret,Laptop,Computers,2025-10-19,-2.0,50000.0,...,NaN,NaN,NaN,Individual,Physical Store,Completed,YES,NaN,4.0,NaN
1993,1994,ORD10846,CUST1158,Peter Otieno,Nyeri,Projector,Accessories,2025-01-24,-2.0,25000.0,...,-52500.0,-46500.0,Bank Transfer,Institution,Phone,Pending,Yes,NaN,4.0,2025.0
1994,1995,ORD11881,CUST1212,Peter Otieno,Kisumu,Projector,Computers,2026-09-24,1.0,25000.0,...,21250.0,20450.0,Cash,Institution,Phone,NaN,No,Dissatisfied,4.0,2026.0
1995,1996,ORD11410,CUST1119,David Kariuki,Nyeri,Projector,Computers,2026-08-12,10.0,50000.0,...,425000.0,395000.0,Mobile Money,Business,Physical Store,Pending,no,NaN,3.0,2025.0
1996,1997,ORD11515,CUST1230,Amina Hassan,Westlands,UPS,Accessories,2026-07-21,5.0,-500.0,...,NaN,NaN,Bank Transfer,Institution,Online,Pending,YES,Satisfied,5.0,2026.0
1997,1998,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0
1998,1999,ORD10830,CUST1304,Peter Otieno,Thika,Desktop,Accessories,2025-11-02,5.0,85000.0,...,382500.0,207500.0,Cash,Institution,NaN,Completed,No,NaN,1.0,2025.0
1999,2000,ORD10859,CUST1318,Peter Otieno,Eldoret,Mouse,Computers,2026-06-18,1.0,25000.0,...,22500.0,14500.0,Mobile Money,Individual,Online,NaN,no,Dissatisfied,4.0,2026.0

In [20]:
df.index

RangeIndex(start=0, stop=2000, step=1)

In [21]:
df["No."].head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: No., dtype: int64

In [22]:
df["No."].tail(10)

1990    1991
1991    1992
1992    1993
1993    1994
1994    1995
1995    1996
1996    1997
1997    1998
1998    1999
1999    2000
Name: No., dtype: int64

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
df.head(10)

,No.,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,1,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,2,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,3,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,4,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,5,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0
5,6,ORD10005,CUST1137,John Mwangi,Nakuru,UPS,Networking,2025-02-27,5.0,1500.0,...,6750.0,-83250.0,Card,NaN,NaN,NaN,No,Dissatisfied,2.0,2025.0
6,7,ORD10006,CUST1185,Mary Wanjiku,Thika,Projector,Office Equipment,2026-07-29,10.0,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Cancelled,No,NaN,5.0,2025.0
7,8,ORD10007,CUST1128,David Kariuki,Nairobi CBD,Desktop,Networking,2026-01-30,NaN,-500.0,...,NaN,NaN,Mobile Money,Individual,Phone,NaN,No,NaN,1.0,NaN
8,9,ORD10008,CUST1430,NaN,Nakuru,Monitor,Networking,2025-09-27,3.0,5000.0,...,15750.0,-8250.0,Card,Individual,Phone,NaN,Yes,Satisfied,3.0,2026.0
9,10,ORD10009,CUST1043,NaN,Nyeri,Desktop,Accessories,2025-09-03,1.0,25000.0,...,NaN,NaN,Card,NaN,Online,Pending,NaN,NaN,2.0,NaN